apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer-{{ .Values.env_domain }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/whitelist-source-range: 82.209.219.176,51.104.229.140,20.68.4.164,51.11.11.81
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
      more_set_headers "Content-Security-Policy frame-src https://*.glowfinsvs.com https://*.adyen.com https://*.cdn-net.com https://*.surveymonkey.com;frame-ancestors https://*.glowfinsvs.com https://*.samsung.com https://*.surveymonkey.com;connect-src 'self' https://*.glowfinsvs.com wss://*.glowfinsvs.com https://*.google-analytics.com https://*.adyen.com https://*.cdn-net.com https://*.microsoftonline.com https://*.surveymonkey.com;upgrade-insecure-requests;";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: SAMEORIGIN";

  name: {{ .Values.env_domain }}-swagger
spec:
#SSL
  tls:
  - hosts:
    - "*.{{ .Values.env_domain }}.glowfinsvs.com"
    secretName: {{ .Values.env_domain }}-tls

#Rules
  rules:

  - host: platform.{{ .Values.env_domain }}.glowfinsvs.com
    http:
      paths:
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.glowapi }}
            port:
              name: http